export const universityData = [
  // Top 300+ Universities from uniRank 2025
  { name: "Massachusetts Institute of Technology", state: "Massachusetts" },
  { name: "Harvard University", state: "Massachusetts" },
  { name: "Stanford University", state: "California" },
  { name: "Cornell University", state: "New York" },
  { name: "University of California, Berkeley", state: "California" },
  { name: "University of Washington", state: "Washington" },
  { name: "University of Michigan", state: "Michigan" },
  { name: "Columbia University", state: "New York" },
  { name: "University of Pennsylvania", state: "Pennsylvania" },
  { name: "Yale University", state: "Connecticut" },
  { name: "University of California, Los Angeles", state: "California" },
  { name: "University of Wisconsin-Madison", state: "Wisconsin" },
  { name: "The University of Texas at Austin", state: "Texas" },
  { name: "University of Minnesota Twin Cities", state: "Minnesota" },
  { name: "Purdue University", state: "Indiana" },
  { name: "University of Chicago", state: "Illinois" },
  { name: "New York University", state: "New York" },
  { name: "Princeton University", state: "New Jersey" },
  { name: "University of California, Davis", state: "California" },
  { name: "University of California, San Diego", state: "California" },
  { name: "University of Florida", state: "Florida" },
  { name: "University of Southern California", state: "California" },
  { name: "Carnegie Mellon University", state: "Pennsylvania" },
  { name: "Johns Hopkins University", state: "Maryland" },
  { name: "Duke University", state: "North Carolina" },
  { name: "University of Illinois Urbana-Champaign", state: "Illinois" },
  { name: "Michigan State University", state: "Michigan" },
  { name: "Arizona State University", state: "Arizona" },
  { name: "University of North Carolina at Chapel Hill", state: "North Carolina" },
  { name: "Rutgers University", state: "New Jersey" },
  { name: "Texas A&M University", state: "Texas" },
  { name: "University of Colorado Boulder", state: "Colorado" },
  { name: "University of Maryland", state: "Maryland" },
  { name: "University of Virginia", state: "Virginia" },
  { name: "The University of Arizona", state: "Arizona" },
  { name: "Northwestern University", state: "Illinois" },
  { name: "The Ohio State University", state: "Ohio" },
  { name: "University of California, Irvine", state: "California" },
  { name: "Washington University in St. Louis", state: "Missouri" },
  { name: "North Carolina State University", state: "North Carolina" },
  { name: "Penn State University", state: "Pennsylvania" },
  { name: "Boston University", state: "Massachusetts" },
  { name: "Indiana University Bloomington", state: "Indiana" },
  { name: "The University of Utah", state: "Utah" },
  { name: "University of Pittsburgh", state: "Pennsylvania" },
  { name: "Virginia Tech", state: "Virginia" },
  { name: "Brigham Young University", state: "Utah" },
  { name: "University of California, Santa Barbara", state: "California" },
  { name: "Georgetown University", state: "District of Columbia" },
  { name: "University of Nebraska-Lincoln", state: "Nebraska" },
  { name: "Georgia Institute of Technology", state: "Georgia" },
  { name: "Tufts University", state: "Massachusetts" },
  { name: "University of Georgia", state: "Georgia" },
  { name: "Brown University", state: "Rhode Island" },
  { name: "Oregon State University", state: "Oregon" },
  { name: "University of Rochester", state: "New York" },
  { name: "California Institute of Technology", state: "California" },
  { name: "University of Iowa", state: "Iowa" },
  { name: "University of Massachusetts Amherst", state: "Massachusetts" },
  { name: "George Washington University", state: "District of Columbia" },
  { name: "George Mason University", state: "Virginia" },
  { name: "Iowa State University", state: "Iowa" },
  { name: "Colorado State University", state: "Colorado" },
  { name: "University at Buffalo", state: "New York" },
  { name: "University of Connecticut", state: "Connecticut" },
  { name: "Vanderbilt University", state: "Tennessee" },
  { name: "University of California, San Francisco", state: "California" },
  { name: "Syracuse University", state: "New York" },
  { name: "Florida State University", state: "Florida" },
  { name: "University of Houston", state: "Texas" },
  { name: "University of Oregon", state: "Oregon" },
  { name: "Washington State University", state: "Washington" },
  { name: "University of Notre Dame", state: "Indiana" },
  { name: "Emory University", state: "Georgia" },
  { name: "University of South Florida", state: "Florida" },
  { name: "Rice University", state: "Texas" },
  { name: "Dartmouth College", state: "New Hampshire" },
  { name: "University of California, Santa Cruz", state: "California" },
  { name: "University of Illinois Chicago", state: "Illinois" },
  { name: "University of Kentucky", state: "Kentucky" },
  { name: "University of California, Riverside", state: "California" },
  { name: "University of Central Florida", state: "Florida" },
  { name: "Georgia State University", state: "Georgia" },
  { name: "University of Kansas", state: "Kansas" },
  { name: "University of Missouri", state: "Missouri" },
  { name: "University of Delaware", state: "Delaware" },
  { name: "Northeastern University", state: "Massachusetts" },
  { name: "University of South Carolina", state: "South Carolina" },
  { name: "University of New Mexico", state: "New Mexico" },
  { name: "University of Miami", state: "Florida" },
  { name: "The University of Tennessee, Knoxville", state: "Tennessee" },
  { name: "Louisiana State University", state: "Louisiana" },
  { name: "Rochester Institute of Technology", state: "New York" },
  { name: "Boston College", state: "Massachusetts" },
  { name: "University of Cincinnati", state: "Ohio" },
  { name: "University of North Texas", state: "Texas" },
  { name: "Temple University", state: "Pennsylvania" },
  { name: "San Diego State University", state: "California" },
  { name: "The University of Oklahoma", state: "Oklahoma" },
  { name: "Drexel University", state: "Pennsylvania" },
  { name: "Florida International University", state: "Florida" },
  { name: "University of Vermont", state: "Vermont" },
  { name: "University of New Hampshire", state: "New Hampshire" },
  { name: "Case Western Reserve University", state: "Ohio" },
  { name: "Clemson University", state: "South Carolina" },
  { name: "Fordham University", state: "New York" },
  { name: "Virginia Commonwealth University", state: "Virginia" },
  { name: "Oklahoma State University", state: "Oklahoma" },
  { name: "Utah State University", state: "Utah" },
  { name: "American University", state: "District of Columbia" },
  { name: "The University of Alabama", state: "Alabama" },
  { name: "University of Hawaii at Manoa", state: "Hawaii" },
  { name: "Kansas State University", state: "Kansas" },
  { name: "Binghamton University", state: "New York" },
  { name: "University of Arkansas", state: "Arkansas" },
  { name: "Wake Forest University", state: "North Carolina" },
  { name: "University of Mississippi", state: "Mississippi" },
  { name: "University of Nevada, Reno", state: "Nevada" },
  { name: "Stony Brook University", state: "New York" },
  { name: "University of Rhode Island", state: "Rhode Island" },
  { name: "University of Louisville", state: "Kentucky" },
  { name: "Tulane University", state: "Louisiana" },
  { name: "University of Denver", state: "Colorado" },
  { name: "Marquette University", state: "Wisconsin" },
  { name: "Illinois State University", state: "Illinois" },
  { name: "University of Maine", state: "Maine" },
  { name: "Ohio University", state: "Ohio" },
  { name: "University of North Carolina at Charlotte", state: "North Carolina" },
  { name: "University of Memphis", state: "Tennessee" },
  { name: "Auburn University", state: "Alabama" },
  { name: "University of Wyoming", state: "Wyoming" },
  { name: "Montana State University", state: "Montana" },
  { name: "University of Montana", state: "Montana" },
  { name: "West Virginia University", state: "West Virginia" },
  { name: "University of Idaho", state: "Idaho" },
  { name: "University of Alaska Fairbanks", state: "Alaska" },
  { name: "University of North Dakota", state: "North Dakota" },
  { name: "University of South Dakota", state: "South Dakota" },
  { name: "Southern Methodist University", state: "Texas" },
  { name: "Texas Christian University", state: "Texas" },
  { name: "Baylor University", state: "Texas" },
  { name: "Texas Tech University", state: "Texas" },
  { name: "University of Houston - Downtown", state: "Texas" },
  { name: "Sam Houston State University", state: "Texas" },
  { name: "Stephen F. Austin State University", state: "Texas" },
  { name: "University of North Texas at Dallas", state: "Texas" },
  { name: "California State University, Long Beach", state: "California" },
  { name: "California State University, Fullerton", state: "California" },
  { name: "California State University, Northridge", state: "California" },
  { name: "San Francisco State University", state: "California" },
  { name: "San Jose State University", state: "California" },
  { name: "California State University, Sacramento", state: "California" },
  { name: "California State University, Fresno", state: "California" },
  { name: "California State Polytechnic University, Pomona", state: "California" },
  { name: "University of the Pacific", state: "California" },
  { name: "Pepperdine University", state: "California" },
  { name: "Loyola Marymount University", state: "California" },
  { name: "Santa Clara University", state: "California" },
  { name: "Chapman University", state: "California" },
  { name: "Occidental College", state: "California" },
  { name: "Pomona College", state: "California" },
  { name: "Claremont McKenna College", state: "California" },
  { name: "Harvey Mudd College", state: "California" },
  { name: "Scripps College", state: "California" },
  { name: "Pitzer College", state: "California" },
  { name: "University of San Diego", state: "California" },
  { name: "Villanova University", state: "Pennsylvania" },
  { name: "Lehigh University", state: "Pennsylvania" },
  { name: "Lafayette College", state: "Pennsylvania" },
  { name: "Bucknell University", state: "Pennsylvania" },
  { name: "Dickinson College", state: "Pennsylvania" },
  { name: "Franklin & Marshall College", state: "Pennsylvania" },
  { name: "Gettysburg College", state: "Pennsylvania" },
  { name: "Swarthmore College", state: "Pennsylvania" },
  { name: "Haverford College", state: "Pennsylvania" },
  { name: "Bryn Mawr College", state: "Pennsylvania" },
  { name: "Amherst College", state: "Massachusetts" },
  { name: "Williams College", state: "Massachusetts" },
  { name: "Wellesley College", state: "Massachusetts" },
  { name: "Smith College", state: "Massachusetts" },
  { name: "Mount Holyoke College", state: "Massachusetts" },
  { name: "Brandeis University", state: "Massachusetts" },
  { name: "College of the Holy Cross", state: "Massachusetts" },
  { name: "Worcester Polytechnic Institute", state: "Massachusetts" },
  { name: "Babson College", state: "Massachusetts" },
  { name: "Bentley University", state: "Massachusetts" },
  { name: "Olin College of Engineering", state: "Massachusetts" },
  { name: "Barnard College", state: "New York" },
  { name: "Vassar College", state: "New York" },
  { name: "Colgate University", state: "New York" },
  { name: "Hamilton College", state: "New York" },
  { name: "Rensselaer Polytechnic Institute", state: "New York" },
  { name: "Skidmore College", state: "New York" },
  { name: "Union College", state: "New York" },
  { name: "Hobart and William Smith Colleges", state: "New York" },
  { name: "Ithaca College", state: "New York" },
  { name: "Clarkson University", state: "New York" },
  { name: "St. Lawrence University", state: "New York" },
  { name: "Marist College", state: "New York" },
  { name: "Pace University", state: "New York" },
  { name: "Hofstra University", state: "New York" },
  { name: "Adelphi University", state: "New York" },
  { name: "The New School", state: "New York" },
  { name: "Pratt Institute", state: "New York" },
  { name: "School of Visual Arts", state: "New York" },
  { name: "Fashion Institute of Technology", state: "New York" },
  { name: "Juilliard School", state: "New York" },
  { name: "Cooper Union", state: "New York" },
  { name: "Webb Institute", state: "New York" },
  { name: "United States Military Academy", state: "New York" },
  { name: "United States Naval Academy", state: "Maryland" },
  { name: "United States Air Force Academy", state: "Colorado" },
  { name: "United States Coast Guard Academy", state: "Connecticut" },
  { name: "United States Merchant Marine Academy", state: "New York" },
  { name: "Wesleyan University", state: "Connecticut" },
  { name: "Trinity College", state: "Connecticut" },
  { name: "Connecticut College", state: "Connecticut" },
  { name: "Fairfield University", state: "Connecticut" },
  { name: "Quinnipiac University", state: "Connecticut" },
  { name: "University of Hartford", state: "Connecticut" },
  { name: "Sacred Heart University", state: "Connecticut" },
  { name: "Middlebury College", state: "Vermont" },
  { name: "Bennington College", state: "Vermont" },
  { name: "Champlain College", state: "Vermont" },
  { name: "Norwich University", state: "Vermont" },
  { name: "Bowdoin College", state: "Maine" },
  { name: "Colby College", state: "Maine" },
  { name: "Bates College", state: "Maine" },
  { name: "College of the Atlantic", state: "Maine" },
  { name: "Providence College", state: "Rhode Island" },
  { name: "Bryant University", state: "Rhode Island" },
  { name: "Salve Regina University", state: "Rhode Island" },
  { name: "Roger Williams University", state: "Rhode Island" },
  { name: "Davidson College", state: "North Carolina" },
  { name: "Elon University", state: "North Carolina" },
  { name: "High Point University", state: "North Carolina" },
  { name: "Appalachian State University", state: "North Carolina" },
  { name: "East Carolina University", state: "North Carolina" },
  { name: "University of North Carolina Wilmington", state: "North Carolina" },
  { name: "University of North Carolina Greensboro", state: "North Carolina" },
  { name: "College of Charleston", state: "South Carolina" },
  { name: "The Citadel", state: "South Carolina" },
  { name: "Furman University", state: "South Carolina" },
  { name: "Wofford College", state: "South Carolina" },
  { name: "University of Richmond", state: "Virginia" },
  { name: "William & Mary", state: "Virginia" },
  { name: "James Madison University", state: "Virginia" },
  { name: "Old Dominion University", state: "Virginia" },
  { name: "Radford University", state: "Virginia" },
  { name: "Christopher Newport University", state: "Virginia" },
  { name: "Liberty University", state: "Virginia" },
  { name: "Regent University", state: "Virginia" },
  { name: "University of Maryland, Baltimore County", state: "Maryland" },
  { name: "Towson University", state: "Maryland" },
  { name: "Loyola University Maryland", state: "Maryland" },
  { name: "Goucher College", state: "Maryland" },
  { name: "Salisbury University", state: "Maryland" },
  { name: "Frostburg State University", state: "Maryland" },
  { name: "Howard University", state: "District of Columbia" },
  { name: "Catholic University of America", state: "District of Columbia" },
  { name: "Trinity Washington University", state: "District of Columbia" },
  { name: "Gallaudet University", state: "District of Columbia" },
  { name: "University of the District of Columbia", state: "District of Columbia" },
  { name: "Delaware State University", state: "Delaware" },
  { name: "Wilmington University", state: "Delaware" },
  { name: "Georgia Southern University", state: "Georgia" },
  { name: "Kennesaw State University", state: "Georgia" },
  { name: "University of West Georgia", state: "Georgia" },
  { name: "Mercer University", state: "Georgia" },
  { name: "Savannah College of Art and Design", state: "Georgia" },
  { name: "Agnes Scott College", state: "Georgia" },
  { name: "Spelman College", state: "Georgia" },
  { name: "Morehouse College", state: "Georgia" },
  { name: "Clark Atlanta University", state: "Georgia" },
  { name: "Rollins College", state: "Florida" },
  { name: "Stetson University", state: "Florida" },
  { name: "University of Tampa", state: "Florida" },
  { name: "Florida Gulf Coast University", state: "Florida" },
  { name: "University of North Florida", state: "Florida" },
  { name: "Florida Atlantic University", state: "Florida" },
  { name: "University of West Florida", state: "Florida" },
  { name: "Nova Southeastern University", state: "Florida" },
  { name: "Lynn University", state: "Florida" },
  { name: "Eckerd College", state: "Florida" },
  { name: "Flagler College", state: "Florida" },
  { name: "University of Alabama at Birmingham", state: "Alabama" },
  { name: "University of Alabama in Huntsville", state: "Alabama" },
];
